version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: chokidar
    versions:
    - ">= 2.1.1.a, < 2.1.2"
  - dependency-name: chokidar
    versions:
    - ">= 2.1.2.a, < 2.1.3"
  - dependency-name: marked
    versions:
    - ">= 0.6.1.a, < 0.6.2"
  - dependency-name: ora
    versions:
    - ">= 3.2.a, < 3.3"
  - dependency-name: tslint
    versions:
    - ">= 5.13.a, < 5.14"
  - dependency-name: ts-node
    versions:
    - ">= 8.0.3.a, < 8.0.4"
  - dependency-name: concurrently
    versions:
    - 6.0.0
    - 6.0.1
  - dependency-name: "@types/fs-extra"
    versions:
    - 9.0.10
    - 9.0.6
    - 9.0.7
    - 9.0.8
    - 9.0.9
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: simple-git
    versions:
    - 2.31.0
    - 2.32.0
    - 2.34.2
    - 2.35.0
    - 2.35.1
    - 2.35.2
    - 2.36.0
    - 2.36.1
    - 2.36.2
    - 2.37.0
  - dependency-name: ora
    versions:
    - 5.3.0
  - dependency-name: tslint-react
    versions:
    - 4.1.0
